global.profile=dev
server.tomcat.max-threads=200

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.default-property-inclusion=NON_NULL

spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

# mybatis
mybatis.config-locations=classpath:mybatis/mybatis-config.xml

# recaptcha
recaptcha.secret=6Lf_zpoiAAAAAGUpHKHyFj9TW9nqdmEReKS98o5M
recaptcha.url=https://www.google.com/recaptcha/api/siteverify

# monitor
management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# database migration
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration

# social production server
spring.security.oauth2.client.registration.google.client-id=154553044730-30tc4s6p9g0hv8usti6l7fpecqa6akrj.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=SbzBqVVM4nTFr7PFUU_ddIZH
spring.security.oauth2.client.registration.google.redirect-uri-template=http://setraopstoapi.pharporpok.com:8443/EstrApp/oauth2/callback/{registrationId}
spring.security.oauth2.client.registration.google.scope=email profile

spring.security.oauth2.client.registration.facebook.client-id=413219592781111
spring.security.oauth2.client.registration.facebook.client-secret=1c2205d5dd5f4fd3417bdc1280eb5a38
spring.security.oauth2.client.registration.facebook.redirect-uri-template=http://setraopstoapi.pharporpok.com:8443/EstrApp/oauth2/callback/{registrationId}
spring.security.oauth2.client.registration.facebook.scope=email public_profile

spring.security.oauth2.client.registration.github.client-id=1f4bf092559de5d3805d
spring.security.oauth2.client.registration.github.client-secret=a8dc00006baf095fac2ab2a7e36299a42e27521d
spring.security.oauth2.client.registration.github.redirect-uri-template=http://setraopstoapi.pharporpok.com:8443/EstrApp/oauth2/callback/{registrationId}
spring.security.oauth2.client.registration.github.scope=user:email read:user

spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v3.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v3.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
