global.api.base-url.accounting=http://192.168.10.10:8080
global.api.base-url.inventory=http://192.168.10.10:8080
global.api.base-url.purchasing=http://192.168.10.10:8080
global.api.base-url.sales=http://192.168.10.10:8080
global.api.base-url.hr=http://192.168.10.10:8080

global.server.from=Server 10.10

global.google-authenticator=false

global.datasource.driverClassName=com.mysql.jdbc.Driver
global.datasource.jdbc-url=jdbc:mysql://192.168.10.10:3306/0030_UT?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
global.datasource.username=udaya
global.datasource.password=P@ssw0rd()


swagger.version=1.0

spring.datasource.driverClassName=${global.datasource.driverClassName}
spring.datasource.jdbc-url=${global.datasource.jdbc-url}
spring.datasource.username=${global.datasource.username}
spring.datasource.password=${global.datasource.password}


server.from=${global.server.from}
google-authenticator=${global.google-authenticator}
