global.api.base-url.accounting=http://qacltom.udaya-tech.lan:8443
global.api.base-url.inventory=http://qacltom.udaya-tech.lan:8443
global.api.base-url.purchasing=http://qacltom.udaya-tech.lan:8443
global.api.base-url.sales=http://qacltom.udaya-tech.lan:8443
global.api.base-url.hr=http://qacltom.udaya-tech.lan:8443

global.server.from=QA

global.google-authenticator=false

global.datasource.driverClassName=com.mysql.jdbc.Driver
global.datasource.jdbc-url=jdbc:mysql://qadbloc.udaya-tech.lan:3306/1140_Libra_CRM_Database?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
global.datasource.username=deDBplut
global.datasource.password=1Wsbrost3*tL& g/u 20!@& 6c3ureP

global.freedom.datasource.driverClassName=com.mysql.jdbc.Driver
global.freedom.datasource.jdbc-url=jdbc:mysql://qadbloc.udaya-tech.lan:3306/1140_Libra_CRM_Database?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
global.freedom.datasource.username=deDBplut
global.freedom.datasource.password=1Wsbrost3*tL& g/u 20!@& 6c3ureP

swagger.version=1.04

spring.datasource.driverClassName=${global.datasource.driverClassName}
spring.datasource.jdbc-url=${global.datasource.jdbc-url}
spring.datasource.username=${global.datasource.username}
spring.datasource.password=${global.datasource.password}

spring.datasource.freedom.driverClassName=${global.freedom.datasource.driverClassName}
spring.datasource.freedom.jdbc-url=${global.freedom.datasource.jdbc-url}
spring.datasource.freedom.username=${global.freedom.datasource.username}
spring.datasource.freedom.password=${global.freedom.datasource.password}

server.from=${global.server.from}
google-authenticator=${global.google-authenticator}
