global.api.base-url.accounting=http://utapinew.udaya.lan:8443
global.api.base-url.inventory=http://utapinew.udaya.lan:8443
global.api.base-url.purchasing=http://utapinew.udaya.lan:8443
global.api.base-url.sales=http://utapinew.udaya.lan:8443
global.api.base-url.hr=https://utapinew.udaya-tech.com

global.server.from=Production

global.google-authenticator=true

global.datasource.driverClassName=com.mysql.jdbc.Driver
global.datasource.jdbc-url=jdbc:mysql://utdbsystem.udaya.lan:3306/1074_NewLink_DBA?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
global.datasource.username=UTApiNeWUsr
global.datasource.password=bw3wf Newpoi 23 Ut1 AApI

global.freedom.datasource.driverClassName=com.mysql.jdbc.Driver
global.freedom.datasource.jdbc-url=jdbc:mysql://utdbsystem.udaya.lan:3306/1121_NewLink_Freedom_DBA?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
global.freedom.datasource.username=UTApiNeWUsr
global.freedom.datasource.password=bw3wf Newpoi 23 Ut1 AApI

swagger.version=1.0

spring.datasource.driverClassName=${global.datasource.driverClassName}
spring.datasource.jdbc-url=${global.datasource.jdbc-url}
spring.datasource.username=${global.datasource.username}
spring.datasource.password=${global.datasource.password}

spring.datasource.freedom.driverClassName=${global.freedom.datasource.driverClassName}
spring.datasource.freedom.jdbc-url=${global.freedom.datasource.jdbc-url}
spring.datasource.freedom.username=${global.freedom.datasource.username}
spring.datasource.freedom.password=${global.freedom.datasource.password}

server.from=${global.server.from}
google-authenticator=${global.google-authenticator}
