global.api.base-url.hr=http://localhost:${server.port}
global.api.base-url.inventory=http://localhost:${server.port}
global.api.base-url.sales=http://localhost:${server.port}
global.api.base-url.accounting=http://localhost:${server.port}

global.server.from=Local

global.google-authenticator=false

global.datasource.driverClassName=com.mysql.jdbc.Driver
global.datasource.jdbc-url=jdbc:mysql://localhost:3307/libra_db_v2?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
global.datasource.username=root
global.datasource.password=


swagger.version=1.0

spring.datasource.driverClassName=${global.datasource.driverClassName}
spring.datasource.jdbc-url=${global.datasource.jdbc-url}
spring.datasource.username=${global.datasource.username}
spring.datasource.password=${global.datasource.password}


server.from=${global.server.from}
google-authenticator=${global.google-authenticator}
