###! Tomcat Production
api.authUrl=${global.api.base-url.inventory}${server.servlet.context-path}/oauth/token




###! Telegram Bot Price Request
telegram.botToken.price-request=1334657747:AAFbhUsr_0RjVa-mxx_bKy99Ij05XM-uNuo
telegram.chatId.price-request=-558259953



###! Telegram Bot Purchase Receive
telegram.botToken.purchase-receive=1334657747:AAFbhUsr_0RjVa-mxx_bKy99Ij05XM-uNuo
telegram.chatId.purchase-receive=-330695593



###! Telegram Bot Expense Request
telegram.botToken.expense-request=1334657747:AAFbhUsr_0RjVa-mxx_bKy99Ij05XM-uNuo
telegram.chatId.expense-request=-1001497355274




