###! Tomcat QA Server
api.authUrl=${global.api.base-url.inventory}${server.servlet.context-path}/oauth/token





###! Telegram Bot Price Request
telegram.botToken.price-request=7184951726:AAHth32ZgP9R685UXTGfBXFSZMopjCojwbw
telegram.chatId.price-request=-4534950648



###! Telegram Bot Purchase Receive
telegram.botToken.purchase-receive=7184951726:AAHth32ZgP9R685UXTGfBXFSZMopjCojwbw
telegram.chatId.purchase-receive=-4534950648



###! Telegram Bot Expense Request
telegram.botToken.expense-request=7184951726:AAHth32ZgP9R685UXTGfBXFSZMopjCojwbw
telegram.chatId.expense-request=-4534950648


