server.servlet.context-path=/libraSystemHrAPi
spring.jmx.default-domain=libra.hr-system-api.com
project.url=http://localhost:8168/utSystemHrAPi
project.name=Libra HR APi

telegram.botToken=7184951726:AAHth32ZgP9R685UXTGfBXFSZMopjCojwbw
telegram.chatId=-1002122875682