#server.tomcat.max-threads=200

########## ! Tomcat Server Production
server.port= 8443
api.authUrl=${global.api.base-url.hr}${server.servlet.context-path}/oauth/token
api.Link = https://utapinew.udaya-tech.com/nlSystemHrAPi
backend.url = https://sw.udaya-tech.com


#######! Telegram Push
telegram.token.facility = 1334657747:AAFbhUsr_0RjVa-mxx_bKy99Ij05XM-uNuo
telegram.chatId.facility = -1001262941489

#########! Telegram Push
telegram.token.todolist = 1334657747:AAFbhUsr_0RjVa-mxx_bKy99Ij05XM-uNuo
telegram.chatId.todolist = -1001333833185

###### Telegram Push Employee
telegram.tokenAttendance = 1334657747:AAFbhUsr_0RjVa-mxx_bKy99Ij05XM-uNuo
telegram.chatIdAttendance = -989172246




# Telegram error notifications
telegram.botToken=1334657747:AAFbhUsr_0RjVa-mxx_bKy99Ij05XM-uNuo
telegram.chatId=-1001262941489
