api.authUrl=${global.api.base-url.hr}${server.servlet.context-path}/oauth/token



#### Telegram Push Daily Report
telegram.token.todolist = 7184951726:AAHth32ZgP9R685UXTGfBXFSZMopjCojwbw
telegram.chatId.todolist = -4534950648

####### Facility
telegram.token.facility = 7184951726:AAHth32ZgP9R685UXTGfBXFSZMopjCojwbw
telegram.chatId.facility = -4534950648

###### Attendance
telegram.tokenAttendance = 7184951726:AAHth32ZgP9R685UXTGfBXFSZMopjCojwbw
telegram.chatIdAttendance = -4534950648



### Recaptcha key
recaptcha.secretQA=6LeQHrMfAAAAANy2n-8n8yvX3iT8OXoCEmZ6Qy9V












# Email
url.project=http://localhost:8168/utSystemHrAPi



# Telegram error notifications
telegram.botToken=7184951726:AAHth32ZgP9R685UXTGfBXFSZMopjCojwbw
telegram.chatId=-4534950648
