spring.config.location=classpath:/application-local.properties

##########! Local (Server 10.10)
server.port= 8080
api.authUrl=${global.api.base-url.hr}${server.servlet.context-path}/oauth/token




########! Server 10.10
#server.port = 8080
#api.authUrl = http://192.168.10.10:8080/nlSystemHrAPi/oauth/token
#server.servlet.context-path= /nlSystemHrAPi
#spring.jmx.default-domain= nl.hr-system-api.com
#server.from = Server 10.10

### database connection default
# spring.datasource.driverClassName = com.mysql.jdbc.Driver
# spring.datasource.jdbc-url = jdbc:mysql://192.168.10.10:3306/1074_NewLink_DBA?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
# spring.datasource.username = udaya
# spring.datasource.password = P@ssw0rd()





# Telegram error notifications
telegram.botToken=7184951726:AAHth32ZgP9R685UXTGfBXFSZMopjCojwbw
telegram.chatId=-1002122875682
