###! Tomcat QA Server
api.authUrl=${global.api.base-url.sales}${server.servlet.context-path}/oauth/token


###! Telegram Bot Sales Order
telegram.botToken.sales-order=7184951726:AAHth32ZgP9R685UXTGfBXFSZMopjCojwbw
telegram.chatId.sales-order=-4534950648



###! Telegram Bot Quotation
telegram.botToken.quotation=7184951726:AAHth32ZgP9R685UXTGfBXFSZMopjCojwbw
telegram.chatId.quotation=-4534950648



###! Telegram Bot Sales Invoice
telegram.botToken.sales-invoice=7184951726:AAHth32ZgP9R685UXTGfBXFSZMopjCojwbw
telegram.chatId.sales-invoice=-4534950648



